AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31

Resources:
  UploadBucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: !Sub '${AWS::StackName}-upload-bucket-${AWS::Region}-${AWS::AccountId}'
    DeletionPolicy: Delete

  SessionsTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: !Sub '${AWS::StackName}-sessions'
      AttributeDefinitions:
        - AttributeName: sessionId
          AttributeType: S
      KeySchema:
        - AttributeName: sessionId
          KeyType: HASH
      ProvisionedThroughput:
        ReadCapacityUnits: 5
        WriteCapacityUnits: 5

  UploadDocumentFunction:
    Type: AWS::Serverless::Function
    Properties:
      Handler: app.upload_document.handler
      Runtime: python3.10
      MemorySize: 512
      Timeout: 30
      Environment:
        Variables:
          S3_BUCKET_NAME: !Ref UploadBucket
          DYNAMODB_TABLE_NAME: !Ref SessionsTable
      Policies:
        - S3CrudPolicy:
            BucketName: !Ref UploadBucket
        - DynamoDBCrudPolicy:
            TableName: !Ref SessionsTable
      Events:
        UploadAPI:
          Type: Api
          Properties:
            Path: /upload
            Method: post
