name: Build and Deploy Server

on:
  push:
    branches:
      - main
    paths:
      - 'server/**'
  pull_request:
    branches:
      - main
    paths:
      - 'server/**'

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout source code
        uses: actions/checkout@v3

      - name: Set up Python environment
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install AWS SAM CLI
        run: |
          pip install --upgrade aws-sam-cli

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1 
      - name: Build SAM Application
        run: |
          sam build

      - name: Deploy SAM Application
        env:
          STACK_NAME: rag-app  # Replace with your stack name
        run: |
          sam deploy \
            --stack-name $STACK_NAME \
            --no-confirm-changeset \
            --no-fail-on-empty-changeset \
            --capabilities CAPABILITY_NAMED_IAM \
            --region us-east-1  # Replace with your AWS region

      - name: Output Stack Outputs
        run: |
          aws cloudformation describe-stacks \
            --stack-name rag-app \
            --query "Stacks[0].Outputs" \
            --region us-east-1  # Replace with your AWS region