name: Deploy Server with AWS SAM

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    timeout-minutes: 30

    steps:
      - name: Checkout source code
        uses: actions/checkout@v3

      - name: Set up Python environment
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install AWS SAM CLI
        run: |
          pip install --upgrade aws-sam-cli

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1

      - name: Validate SAM Template
        working-directory: ./server
        run: |
          sam validate

      - name: Build SAM Application
        working-directory: ./server
        run: |
          sam build

      - name: Deploy SAM Application
        working-directory: ./server
        env:
          STACK_NAME: rag-app
        run: |
          sam deploy \
            --stack-name $STACK_NAME \
            --resolve-s3 \
            --no-confirm-changeset \
            --no-fail-on-empty-changeset \
            --capabilities CAPABILITY_NAMED_IAM \
            --region us-east-1 \
            --parameter-overrides OpenAIAPIKey="${{ secrets.OPENAI_API_KEY }}"